name: meshenv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - arpack=3.9.1
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - geometry-central=0.1.0.2024.10.24
  - glpk=5.0
  - gmp=6.3.0
  - h5py=3.12.1
  - hdf5=1.14.5
  - icu=73.1
  - joblib=1.4.2
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcurl=8.12.1
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - liblapack=3.9.0
  - libnghttp2=1.57.0
  - libnsl=2.0.1
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.13.8
  - libzlib=1.2.13
  - llvm-openmp=19.1.7
  - lz4-c=1.9.4
  - mkl=2023.2.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ncurses=6.5
  - numexpr=2.10.1
  - numpy=2.2.2
  - numpy-base=2.2.2
  - openssl=3.5.0
  - pandas=2.2.3
  - pip=25.1
  - potpourri3d=1.1.0
  - python=3.12.3
  - python-dateutil=2.9.0post0
  - python-igraph=0.11.5
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2024.1
  - readline=8.2
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - setuptools=72.1.0
  - six=1.17.0
  - tbb=2021.8.0
  - tensorly=0.8.2
  - texttable=1.6.4
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - trimesh=4.6.4
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - certifi==2026.1.4
    - charset-normalizer==3.4.4
    - contourpy==1.3.3
    - cycler==0.12.1
    - decorator==5.2.1
    - fonttools==4.61.1
    - idna==3.11
    - jinja2==3.1.6
    - kiwisolver==1.4.9
    - lazy-loader==0.4
    - markupsafe==3.0.3
    - matplotlib==3.10.8
    - mne==1.11.0
    - packaging==25.0
    - pillow==12.1.0
    - platformdirs==4.5.1
    - pooch==1.8.2
    - pyparsing==3.3.1
    - requests==2.32.5
    - robust-laplacian==1.0.0
    - tqdm==4.67.1
    - urllib3==2.6.3
